### ISSUE TITLE
Custom styles are not overwriting defaults

### ISSUE THREAD

**Issue by sabi1981** [NyashaNziramasanga/react-native-horizontal-scroll-menu#1]
https://github.com/NyashaNziramasanga/react-native-horizontal-scroll-menu/blob/2570bb5dd88800e8b06318f74d2e8ba1b1741183/src/index.tsx#L93

Hi, 
Didn't you mean:

```<View style={[styles.scrollAreaStyle, scrollAreaStyle]}>```

**Comment by NyashaNziramasanga** [comment]
@sabi1981 thanks for this and resolved on this [PR](https://github.com/NyashaNziramasanga/react-native-horizontal-scroll-menu/pull/4)
